PestControl Full/ASPNetMVCExtendingIdentity2Roles/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPNetMVCExtendingIdentity2Roles.App_code;
using NHibernate;
using PestControl.Model.Entity;
using PestControl.Services;
using ASPNetMVCExtendingIdentity2Roles.Models;
using PestControl.Core;

namespace ASPNetMVCExtendingIdentity2Roles.Controllers
{
    public class ClientController : Controller
    {
        //
        // GET: /Client/
        private readonly IMenuService _menuService;
        private readonly IGalleryService _galleryService;
        private readonly IPaymentService _paymentService;
        private readonly IEmailService _emailService;
        private readonly IContactService _contactService;
        private ISession _session;
        private ISessionFactory _sessionFactory;
        private string _storageRoot;

         private void CreateSession()
        {
            _sessionFactory = new NhSessionFactory().GetSessionFactory();
            _session = _sessionFactory.OpenSession();
        }
         public ClientController()
        {
            CreateSession();
            _emailService = new PestControl.Services.EmailService();
            _menuService = new MenuService(_session);
            _galleryService = new GalleryService(_session);
            _paymentService = new PaymentService(_session);
            _contactService = new ContactService(_session);
           _storageRoot = "media";
        }
         public ActionResult Index()
         {
             return View("_HomePageLayout");
             //return View("_template");
         }

        public ActionResult GalleryView()
        {
            IList<Gallery> galleryList = _galleryService.GetOk();
            ViewBag.GalleryObjList = galleryList;
            return View("GalleryView", galleryList);
        }

        public ActionResult Services()
        {
            return View("_ServicePageLayout");
        }
        public ActionResult Contact(string mes)
        {
            var model = new ContactViewModel();
            if (mes.IsNotNullOrWhiteSpace())
            {
                ViewBag.SuccessMessage = mes;
            }
            return View("");
        }

        [HttpPost]
        public ActionResult Contact(ContactViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            var scedual = DateTime.UtcNow;
            //DateTime.TryParse(model.Schedual, out scedual);

            var contact = new Contact
            {
                Address = model.Address,
                City = model.City,
                ContactStatus = ContactStatusText.Pending,
                CreationDate = DateTime.UtcNow,
                ModificationDate = DateTime.UtcNow,
                Phone = model.Phone,
                Schedual = model.Schedual,
                State = model.State,
                ZipCode = model.PostalCode,
                FirstName = model.Firstname,
                LastName = model.LastName,
                Email = model.Email,
                Message = model.Message
            };
            _contactService.Save(contact);
            var message = "Your contact request successfully submitted";

            _emailService.SendScheduleRequestToAdmin(contact.FirstName + " " + contact.LastName, contact);
            _emailService.SendScheduleRequestSubmitConfirmationToClient(contact.FirstName + " " + contact.LastName, contact);
            return RedirectToAction("Contact", new { mes = message });
        }

        public ActionResult Payment(string mes)
        {
            var model = new PaymentEditModel
            {
                AvaiableTypes = _paymentService.GetAllTypes().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList()
            };

            if(mes.IsNotNullOrWhiteSpace())
            {
                ViewBag.SuccessMessage = mes;
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult Payment(PaymentEditModel model)
        {
            model.AvaiableTypes = _paymentService.GetAllTypes().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
            if (!ModelState.IsValid) return View(model);

            var expireDate = DateTime.UtcNow;
            //DateTime.TryParse(model.ExpireDate, out expireDate);
            var cardNo = model.CardNo.Replace(" ", "");
            var payment = new Payment
            {
                FirstName = model.Firstname,
                LastName = model.LastName,
                Email = model.Email,
                Amount = model.Amount,
                Address = model.Address,
                City = model.City,
                State = model.State,
                ZipCode = model.PostalCode,
                CardNo = cardNo,
                SecurityCode = model.SecurityCode,
                CreationDate = DateTime.UtcNow,
                ModificationDate = DateTime.UtcNow,
                Phone = model.Phone,
                InvoiceNo = model.Invoice,
                Message = model.Message,
                ExpireDate = model.ExpireDate   ,
                CardType = _paymentService.GetCardType(Convert.ToInt64(model.CardType))
            };

            _paymentService.Save(payment);

            var adminEmail = App.Configurations.AdminEmail.Value;

            _emailService.SendPaymentMessage(payment.Email, payment, false);
            _emailService.SendPaymentMessage(adminEmail, payment, true);

            var message = "Your payment is successfull";

            return RedirectToAction("Payment", new { mes = message });
        }

        public ActionResult ConfirmContactApproval(long id)
        {
            var contact = _contactService.GetContact(id);

            if(contact != null)
            {
                if (contact.ContactStatus == 2)
                {
                    var message = "Your schedule request link is already approved! please contact with our office.";
                    return RedirectToAction("Contact", new { mes = message });
                }
                else if(contact.ContactStatus == 0){
                    var message = "Your schedule request link is not approved by office! please contact with our office.";
                    return RedirectToAction("Contact", new { mes = message });
                }
                else
                {
                    bool isConfirmed = _contactService.ChangeContactStatus(contact, ContactStatusText.Confirmed);
                    if (isConfirmed)
                    {
                        var message = "Your schedule request is approved! Office will contact you soon!";
                        string name = contact.FirstName + " " + contact.LastName;
                        _emailService.SendContactConfirmationApprovalNotificationEmailToAdmin(name, contact);
                        return RedirectToAction("Contact", new { mes = message }); 
                    }
                    else
                    {
                        var message = "Something went wrong! please contact with our office.";
                        return RedirectToAction("Contact", new { mes = message });
                    }
                }
            }
            else
            {
                var message = "Your schedule request link is not valid one! please contact with our office.";
                return RedirectToAction("Contact", new { mes = message });
            }
        }
	}
}

PestControl Full/ASPNetMVCExtendingIdentity2Roles/Controllers/ImageGalleryController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPNetMVCExtendingIdentity2Roles.App_code;
using NHibernate;
using PestControl.Model.Entity;
using PestControl.Services;

namespace ASPNetMVCExtendingIdentity2Roles.Controllers
{
    public class ImageGalleryController : Controller
    {
        // GET: ImageGallery
        private readonly IMenuService _menuService;
        private readonly IGalleryService _galleryService;
        private ISession _session;
        private ISessionFactory _sessionFactory;
        private string _storageRoot;
        List<string> array = new List<String>();
        private void CreateSession()
        {
            _sessionFactory = new NhSessionFactory().GetSessionFactory();
            _session = _sessionFactory.OpenSession();
        }
        public ImageGalleryController()
        {
            CreateSession();
            _menuService = new MenuService(_session);
            _galleryService = new GalleryService(_session);
            _storageRoot = "media";
        }


        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            IList<Gallery> galleryList = _galleryService.GetOk();
            var imageObj = new GalleryImages();
            ViewBag.gallery = new SelectList(galleryList, "Id", "Name");
            return View(imageObj);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(GalleryImages galleryImage,long Gallery)
        {
            TempData["GalleryImageObj"] = galleryImage;
            TempData["GalleryId"] = Gallery;
            return View("ImageUpload");
        }

        [Authorize]
        public string Thumbnail(int width, int height, string fileName, string filePath)
        {
            var thumbImageFile = Path.Combine(Server.MapPath("~/Images/Thumb"), fileName);
            //thumbImageFile += ".png";
            using (var srcImage = Image.FromFile(filePath))
            using (var newImage = new Bitmap(width, height))
            using (var graphics = Graphics.FromImage(newImage))
            using (var stream = new MemoryStream())
            {
                graphics.SmoothingMode = SmoothingMode.AntiAlias;
                graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;
                graphics.DrawImage(srcImage, new Rectangle(0, 0, width, height));
                newImage.Save(stream, ImageFormat.Png);
                newImage.Save(thumbImageFile, ImageFormat.Png);
                return thumbImageFile;
            }
        }
        [HttpPost]
        [Authorize]
        public ActionResult SaveGalleryImages(HttpPostedFileBase file)
        {
            var galleryImage = (GalleryImages)TempData["GalleryImageObj"];
            string thumbImageFile = "";
            if (file != null && file.ContentLength > 0)
            {
                var validImageType = new string[] { ".png", ".PNG", ".jpg", ".JPG", ".bmp", ".BMP", ".jpeg", ".JPEG", ".gif", ".GIF" };
                string defaultFileUrl = System.IO.Path.GetFileName(file.FileName);
                string filePath = System.IO.Path.Combine(
                                   Server.MapPath("/Images/GalleryImages/"), defaultFileUrl);
                foreach (string vit in validImageType)
                {
                    if (file.FileName.EndsWith(vit))
                    {
                        var fileName = file.FileName;
                        
                        //array.Add(filePath);
                        var fileInfo = new FileInfo(filePath);
                        if (fileInfo.Exists)
                        {
                            filePath = System.IO.Path.Combine(
                                   Server.MapPath("/Images/GalleryImages"), Guid.NewGuid().ToString().Substring(0, 10) + defaultFileUrl);
                            file.SaveAs(filePath);
                            thumbImageFile = Thumbnail(100, 100, fileName, filePath);
                            //array.Add(filePath);
                            break;
                        }
                        else
                        {
                            file.SaveAs(filePath);
                            thumbImageFile = Thumbnail(120, 80, fileName, filePath);
                            //array.Add(filePath);
                            break;
                        }
                    }
                }
                //bool isGalleryExit = _galleryService.IsGalleryExits(galleryImage.Name);
                //if (!isGalleryExit)
                //{
                    IList<GalleryImages> galleryImageses = new List<GalleryImages>();
                    //foreach (var pImage in array)
                   // {
                        GalleryImages galleryImages = new GalleryImages();
                        galleryImages.CreationDate = DateTime.Now;
                        galleryImages.ModificationDate = DateTime.Now;
                        galleryImages.ImageUrl = filePath;
                        galleryImages.ThumbUrl = thumbImageFile;
                        long galleryId =(long)TempData["GalleryId"];
                        Gallery gallery = _galleryService.LoadById(galleryId);
                        galleryImages.Gallery = gallery;
                        gallery.GalleryImages.Add(galleryImages);
                        _galleryService.Update(gallery);
                    //}
                //}
                //else
                //{

                //}
                    
            }
            return RedirectToAction("Dashboard", new {message ="Image Uploaded Successfully"});
        }

        [Authorize]
        public ActionResult Dashboard(string message = "")
        {
            if (!String.IsNullOrEmpty(message))
            {
                ViewBag.SuccessMessage = message;
            }
            return View();
        }
    }
    
}

PestControl Full/ASPNetMVCExtendingIdentity2Roles/Views/Shared/_AdminPageLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - AlfaJ Admin </title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/typicons.min.css" rel="stylesheet" />
    <link href="~/Content/selectize.css" rel="stylesheet" />
    <link href="~/Content/selectize.default.css" rel="stylesheet" />
    <link href="~/Content/default.css" rel="stylesheet" />
    <link href="~/Content/simplr.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/responsive.css" rel="stylesheet" />
    <link href="~/Content/animate.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,700,600,500,900,800' rel='stylesheet' type='text/css'>

    @*<link href="~/Scripts/file-uploader/css/jquery.fileupload.css" rel="stylesheet" />
        <link href="~/Scripts/file-uploader/css/jquery.fileupload-ui.css" rel="stylesheet" />*@
    @RenderSection("css", required: false)
    <!--[if lt IE 9]>
        <link href="~/Contents/styles-ie8.css" rel="stylesheet">
    <![endif]-->
    <!-- jquery Respond Plugin for IE8 -->
    <script src="~/Scripts/respond.js"></script>
    <script src="~/Scripts/admin/html5shiv.js"></script>

</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-custom" class="animated fadeIn delay1">
    <div class="wrapper">
        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand " href="@Url.Action("LogIn","Account")">
                        <h1 class="fontawesome-icon"></h1>
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-left navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                        <li class="hidden">
                            <a href="#page-top"></a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        @if (HttpContext.Current.User.Identity.IsAuthenticated)
                        {
                            if (HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("ContentAdmin"))
                            {
                                <li class="page-scroll">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="@Url.Action("EditMenu", "Admin")">Add Menu</a></li>
                                        <li><a href="@Url.Action("MenuList", "Admin")">Manage Menu</a></li>
                                    </ul>

                                </li>
                                <li class="page-scroll">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="@Url.Action("EditSubMenu", "Admin")"> Add Services</a></li>
                                        <li><a href="@Url.Action("SubMenuList", "Admin", new { })">Manage Services</a></li>
                                    </ul>
                                </li>

                                <li class="page-scroll">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Gallery <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="@Url.Action("CreateGallery", "Admin")">Add Gallery</a></li>
                                        <li><a href="@Url.Action("GaleryList", "Admin")">Manage Gallery</a></li>
                                        <li><a href="@Url.Action("Create", "ImageGallery")">Add Images</a></li>
                                    </ul>

                                </li>
                            }
                            <li class="page-scroll">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    @if (HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("PaymentAdmin"))
                                    {
                                        <li><a href="@Url.Action("PaymentList", "Admin")">Payment List</a></li>
                                    }
                                    @if (HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("ContactAdmin"))
                                    {
                                        <li><a href="@Url.Action("ContactList", "Admin")">Schedule Request</a></li>    
                                    }
                                </ul>
                            </li>
                            <li><a href="@Url.Action("LogOff", "Account")">Sign Out</a></li>
                        }

                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>
        <section class="page-content">
            <section class="container">
                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger">
                        <a class="close" data-dismiss="alert">×</a>
                        @ViewBag.ErrorMessage
                    </div>
                }
                @if (ViewBag.SuccessMessage != null)
                {
                    <div style="padding-left: 31%" class="alert alert-success">
                        <a class="close" data-dismiss="alert">×</a>
                        <strong>Success!</strong> @ViewBag.SuccessMessage
                    </div>
                }
                @if (ViewBag.InfoMessage != null)
                {

                    <div class="alert alert-info">
                        <a class="close" data-dismiss="alert">×</a>
                        <strong>Info! </strong>@ViewBag.InfoMessage
                    </div>
                }
            </section>
            <div class="mainbodycontent" style="margin: 0 auto;width: 70%">
                @RenderBody()
            </div>

        </section>
        <!-- footer -->
        <section id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-8 col-lg-8">
                        <p>&copy; Copyright 2015 - # - All Rights Reserved.</p>
                    </div><!-- col lg 6 -->
                </div><!-- row -->
            </div><!-- container -->
        </section>
        <!-- footer -->
        <div class="dropdown-bg"></div>
    </div>
    <!-- Core JavaScript Files -->

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/admin/jquery-ui-1.10.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/admin/jquery.easing.min.js"></script>
    <script src="~/Scripts/admin/jquery.masonry-3.1.5.js"></script>
    <script src="~/Scripts/admin/selectize.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/Scripts/admin/simplr.js"></script>
    <script src="~/Scripts/admin/modernizr.custom.js"></script>
    <script src="~/Scripts/admin/toucheffects.js"></script>
    <script src="~/Scripts/admin/heartcode-canvasloader-min.js"></script>
    <script src="~/Scripts/admin/services.js"></script>
    <script src="~/Scripts/admin/scripts.js"></script>
    <script src="~/Scripts/admin/locationLookup.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

PestControl Full/ASPNetMVCExtendingIdentity2Roles/Views/Shared/_MainPagePartialLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="softcoder.net">
    <title>AlfaJ</title>
    <link rel="favicon" href="~/Content/assets/images/favicon.png">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="~/Content/assets/css/bootstrap.min.css">
    <link href="~/Content/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/assets/css/font-awesome.min.css">
    <!-- Custom styles for our template -->
    <link rel="stylesheet" href="~/Content/assets/css/bootstrap-theme.css" media="screen">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/da-slider.css" />
    <link href="~/Content/assets/css/isotope.css" rel="stylesheet" />
    <link href="~/Content/assets/js/fancybox/jquery.fancybox.css" rel="stylesheet" />

    
    @*<link href="~/Scripts/zebra_datepicker/css/bootstrap.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="~/Content/assets/css/style.css">
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="~/Content/assets/js/html5shiv.js"></script>
        <script src="~/Content/assets/js/respond.min.js"></script>
        <![endif]-->
    <style type="text/css">
        .fancybox-wrap {
            z-index:9999!important;
        }
    </style>
</head>
<body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top headroom">
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#" id="logo"><img src="~/Content/assets/images/logo.jpg" alt="pestControl"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right " id="SiteMenu">
                    
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
    <!-- /.navbar -->
    <div class="mainSiteContent">
        <header id="head" class="secondary"></header>
        <section class="container">
            @if (ViewBag.ErrorMessage != null)
            {
                <br />
                <div class="alert alert-danger">
                    <a class="close" data-dismiss="alert">×</a>
                    @ViewBag.ErrorMessage
                </div>
            }
            @if (ViewBag.SuccessMessage != null)
            {
                <br />
                <div style="padding-left: 31%" class="alert alert-success">
                    <a class="close" data-dismiss="alert">×</a>
                    <strong>Success!</strong> @ViewBag.SuccessMessage
                </div>
            }
            @if (ViewBag.InfoMessage != null)
            {
                <br />
                <div class="alert alert-info">
                    <a class="close" data-dismiss="alert">×</a>
                    <strong>Info! </strong>@ViewBag.InfoMessage
                </div>
            }
        </section>
        @RenderBody()
    </div>
    <div class="footer2">
        <div class="container">
            <div class="row">
                <div class="col-md-6 panel">
                    <div class="panel-body">
                        <p class="simplenav">| <a href="@Url.Action("Index","Client")">Home</a> | <a href="@Url.Action("GalleryView", "Client")">Gallery</a> | <a href="@Url.Action("Contact", "Client")">Contact</a> | <a href="@Url.Action("Payment", "Client")">Pay Online</a> |
                    </div>
                </div>
                <div class="col-md-6 panel">
                    <div class="panel-body">
                        <p class="text-right"> Copyright &copy; 2015. <a href="http://alfajpestcontrol.com/" rel="develop">alfajpestcontrol.com</a> </p>
                    </div>
                </div>
            </div>
            <!-- /row of panels -->
        </div>
    </div>

    <!-- JavaScript libs are placed at the end of the document so the pages load faster -->
    <script src="~/Content/assets/js/modernizr-latest.js"></script>
    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
    </script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="~/Content/bootstrap-datetimepicker/js/moment.js"></script>
    <script src="~/Content/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
   
    @*<script src="~/Content/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>*@
    
    
    
    <script src=" ~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Content/assets/js/jquery.cslider.js"></script>
    <script src="~/Content/assets/js/jquery.isotope.min.js"></script>
    <script src="~/Content/assets/js/fancybox/jquery.fancybox.pack.js"></script>
    <script src="~/Content/assets/js/headroom.min.js"></script>
    <script src="~/Content/assets/js/jQuery.headroom.min.js"></script>
    <script src="~/Content/assets/js/custom.js"></script>
    <script>
        $(document).ready(function () {

            jQuery.ajax({
                url: "@Url.RouteUrl("DynamicMenu")",
                type: "GET",
                beforeSend: function () {
                    //jQuery.blockUI({
                    //    timeout: 0,
                    //    message: '<h1><img src="/Content/img/ajax-loader.gif" /> Menu Loading...</h1>'
                    //});
                },
                success: function (response, status, xhr) {
                    //jQuery.unblockUI();
                    //jQuery('.nav').html(response);
                    $('#SiteMenu').html(response);
                },
                complete: function () {
                    // jQuery.unblockUI();
                },
                error: function (response, status, xhr) {
                    //jQuery.unblockUI();
                    console.log("Failed -----");
                    console.log(response);
                }

            });
        });

        //$(document).ready(function () {
        //    var Page = (function () {
        //        var $navArrows = $('#nav-arrows'),
        //        slitslider = $('#slider').slitslider({
        //            autoplay: true
        //        }),
        //        init = function () {
        //            initEvents();
        //        },
        //        initEvents = function () {
        //            $navArrows.children(':last').on('click', function () {
        //                slitslider.next();
        //                return false;
        //            });
        //            $navArrows.children(':first').on('click', function () {
        //                slitslider.previous();
        //                return false;
        //            });
        //        };
        //        return { init: init };
        //    })();
        //    Page.init();

            
        //});
    </script>

    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <script src="~/Content/assets/js/fancybox/jquery.fancybox.pack.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#3").fancybox({
                'autoDimensions': false,
                'width': 350,
                'height': 'auto',
                'top': 20,
                'transitionIn': 'none',
                'transitionOut': 'none'
            });

           });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>